---
title: "Homework 07"
author: "Maddy Degelsmith"
date: "3/17/2021"
output: html_document
---
```{r}
z <- read.table("Homework7.csv",header=TRUE,sep=",", stringsAsFactors=FALSE)
z$myVar <- z$cell_density
str(z$myVar)

```


```{r}
library(ggplot2) # for graphics
library(MASS) # for maximum likelihood estimation

# quick and dirty, a truncated normal distribution to work on the solution set

# z <- rnorm(n=3000,mean=0.2)
# z <- data.frame(1:3000,z) # creating a data frame
# names(z) <- list("ID","myVar") # giving labels to the 2 data variables 
head(z)
z <- z[z$myVar>0,] # only the variables larger than 0 
str(z)
summary(z$myVar)
```

```{r}
# plot a histogram 

p1 <- ggplot(data=z, aes(x=myVar, y=..density..)) +
  geom_histogram(color="grey60",fill="cornsilk",size=0.2) 
print(p1) # plotting a histogram
```

```{r}

# empirical density curve
p1 <-  p1 +  geom_density(linetype="dotted",size=0.75)
print(p1) # a histogram with a dotted line meant to fit really well
```

```{r}

# maximum likelihood parameters for normal
normPars <- fitdistr(z$myVar,"normal") # creating a normal distribution 
print(normPars)
str(normPars)
normPars$estimate["mean"] # note structure of getting a named attribute
```

```{r}
# plot normal probability density
meanML <- normPars$estimate["mean"]
sdML <- normPars$estimate["sd"]

xval <- seq(0,max(z$myVar),len=length(z$myVar))

 stat <- stat_function(aes(x = xval, y = ..y..), fun = dnorm, colour="red", n = length(z$myVar), args = list(mean = meanML, sd = sdML))
 p1 + stat # adding a line to the graph with what the normal distribution should look like - it is the red line, doesn't fit too well
```

```{r}
 # plot exponential probability density
 expoPars <- fitdistr(z$myVar,"exponential")
rateML <- expoPars$estimate["rate"]

stat2 <- stat_function(aes(x = xval, y = ..y..), fun = dexp, colour="blue", n = length(z$myVar), args = list(rate=rateML))
 p1 + stat + stat2 # creating an exponential distribution curve - blue line, still not that close to data
```


```{r}
 # plot uniform probability density
 stat3 <- stat_function(aes(x = xval, y = ..y..), fun = dunif, colour="darkgreen", n = length(z$myVar), args = list(min=min(z$myVar), max=max(z$myVar)))
 p1 + stat + stat2 + stat3

 # the green line is what the graph will look like with uniform density - this is relatively close aside from the large outlier
```


```{r}
# plot beta probability density
 pSpecial <- ggplot(data=z, aes(x=myVar/(max(myVar + 0.1)), y=..density..)) +
  geom_histogram(color="grey60",fill="cornsilk",size=0.2) + 
  xlim(c(0,1)) +
  geom_density(size=0.75,linetype="dotted")

betaPars <- fitdistr(x=z$myVar/max(z$myVar + 0.1),start=list(shape1=1,shape2=2),"beta")
shape1ML <- betaPars$estimate["shape1"]
shape2ML <- betaPars$estimate["shape2"]

statSpecial <- stat_function(aes(x = xval, y = ..y..), fun = dbeta, colour="orchid", n = length(z$myVar), args = list(shape1=shape1ML,shape2=shape2ML))
pSpecial +  
```


```{r}

# the uniform distribution did the best job at fitting the data
length(z$myVar)
# maximum likelihood parameters for uniform
uniformPars <- data.frame(myVar=runif(n=587, min = 42, max = 26825))

mean(uniformPars) # this is the mean
class(uniformPars)
uniformPars$estimate["mean"] # note structure of getting a named attribute

# plot based on the new data and the best fit curve
p1 <- ggplot(data=uniformPars, aes(x=myVar, y=..density..)) +
  geom_histogram(color="grey60",fill="cornsilk",size=0.2) 
print(p1) # plotting a histogram


# plot the line on the new distribution based on the old variables
 stat3 <- stat_function(aes(x = xval, y = ..y..), fun = dunif, colour="darkgreen", n = length(uniformPars$myVar), args = list(min=min(uniformPars$myVar), max=max(uniformPars$myVar)))
 p1+  stat3



```


```{r}
# original data histagram with probability density curve
p2 <- ggplot(data=z, aes(x=myVar, y=..density..)) +
  geom_histogram(color="grey60",fill="cornsilk",size=0.2) 
print(p2)

# density curve
 stat4 <- stat_function(aes(x = xval, y = ..y..), fun = dunif, colour="darkgreen", n = length(z$myVar), args = list(min=min(z$myVar), max=max(z$myVar)))
 p2 +  stat4

```

I think the model did a pretty good job at stimulating realiztid data 